

headers = ["Time",
           "Distance",
           "Engine RPM",
           "Throttle Pos",
           "Engine Temp",
           "G Force Lat",
           "G Force Long",
           "G Force Vert",
           "ADL Temp",
           "5V Aux Supply",
           "8V Aux Supply",
           "Running Lap Time",
           "Comms RS232 Diag",
           "Bat Volts ADL",
           "Lambda 1",
           "Air Temp Inlet",
           "Manifold Pres",
           "Water Temp Post-Radiator",
           "Fuel Actual PW",
           "Fuel Inj Duty",
           "Ign Advance",
           "Brake Pressure Front",
           "Brake Pressure Rear",
           "G Force RSS",
           "Fuel Base PW",
           "Fuel BAP Comp",
           "Fuel AT Comp",
           "Fuel Overall Trim",
           "Wheel Slip (Percent)",
           "Shock Pot Front Right",
           "Shock Pot Front Left",
           "Shock Pot Rear Left",
           "Shock Pot Rear Right",
           "Eng Oil Pres",
           "Fuel Pres",
           "Eng Oil Temp",
           "Bat Volts ECU",
           "Exhaust Temp",
           "Susp Velocity FL",
           "Susp Velocity FR",
           "Susp Velocity RL",
           "Susp Velocity RR",
           "Drive Speed",
           "Ground Speed",
           "Odometer",
           "Lap Number",
           "Thr Pos Change",
           "Oil Pressure Warning",
           "Brake Temp Front",
           "Brake Temp Rear",
           "Calculated Gear Position",
           "Steering Angle",
           "Baro Pres",
           "Fuel Temp",
           "Ign Cut Level Total",
           "Aux 5 Duty ECU",
           "Fuel La Comp",
           "Ign AT Comp",
           "Ign ET Comp",
           "Ign MAP Comp",
           "Pitot Tube 12.5mB",
           "BMAP Temp",
           "No Lift Shift",
           "GPS Sats Used",
           "CAN 1 Bus Utilization",
           "Air Temp Post-Radiator",
           "Air Pressure Pre Radiator",
           "Air Pressure Post Radiator",
           "Water Pump Inlet Pressure",
           "ECU Temp","Lap Distance",
           "Lap Speed",
           "Bat Volts BR2",
           "BR2 Beacon Count",
           "GPS Altitude",
           "Air Tank Pressure",
           "GPS Latitude",
           "GPS Longitude",
           "GPS Heading",
           "GPS Time",
           "GPS Date",
           "GPS Speed",
           "CAN 0 Receive Error Count",
           "CAN 0 Transmit Error Count",
           "CAN 1 Receive Error Count",
           "CAN 1 Transmit Error Count",
           "CAN 0 Bus Utilization",
           "PDM2 Errors",
           "Pneumatic Line Pressure",
           "DRS Pot",
           "Lateral Acceleration",
           "Longitudinal Accel",
           "Yaw Rate",
           "Roll Rate",
           "FAN1 Current",
           "Fuel Cut Level Total",
           "Lap Time",
           "Lap Gain/Loss Running",
           "Comms CAN 1 Diag",
           "Brake Bias Setting",
           "Lap Gain/Loss Final",
           "Zapdos1 Error",
           "Zapdos2 Error",
           "Lap Time Predicted",
           "Sync Rel Pos",
           "Device Up Time",
           "FAN2 Current",
           "FUEL Current",
           "PSM Current",
           "ECU Current",
           "EDL Current",
           "SENSOR Current",
           "AUX Current",
           "FAN1 Health",
           "FAN1 Status",
           "FAN2 Health",
           "FAN2 Status",
           "FUEL Health",
           "FUEL Status",
           "PSM Health",
           "PSM Status",
           "ECU Health",
           "ECU Status",
           "EDL Health",
           "EDL Status",
           "PDM 12V Health",
           "PDM 12V Status",
           "Lap Speed Predicted",
           "Reference Lap Time",
           "AUX Health",
           "AUX Status",
           "SENSOR Health",
           "SENSOR Status",
           "Current Gear Position",
           "Future Gear Position",
           "Zapdos State",
           "DRS Position",
           "Zapdos Error",
           "Misshifts",
           "Launch Mode",
           "Vertical Acceleration",
           "Water Temp Pre-Radiator",
           "Tire Temp Outside Far",
           "Tire Temp Outside Middle",
           "Tire Temp Inside Far",
           "Tire Temp Inside Middle",
           "Water Pump Outlet Pressure",
           "Wheel Speed FL",
           "Wheel Speed FR",
           "Wheel Speed RL",
           "Wheel Speed RR",
           "Radiator 1 Inlet Temp",
           "Shifter Position",
           "Clutch Position",
           "Air Temp Pre-Radiator",
           "Marker Button",
           "Warning Light",
           "Up Shift Light 1",
           "Neutral Switch",
           "Brake Switch",
           "Wheelspin 4",
           "Wheelspin 1",
           "Wheelspin 2",
           "Wheelspin 3",
           "Engine Temperature Warning",
           "Engine Oil Temp Warning",
           "Downshift_Raw_Input",
           "Upshift_Raw_Input",
           "Clutch_Raw_Input",
    
    ]



